name: fl_pip
description: A picture-in-picture plugin for android and ios that can display any flutter view
version: 0.0.1
repository: https://github.com/Wayaer/fl_pip.git

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.fl.pip
        pluginClass: FlPiPPlugin
      ios:
        pluginClass: FlPiPPlugin
  assets:
    - assets/